class ConfigurationFilename:
    PRODUCTION: str = ".env.prod"
    DEVELOPMENT: str = ".env.dev"


class DotenvConfigurationKey:
    MONGODB_CONNECTION_STRING: str = "MONGODB_CONNECTION_STRING"
    MONGODB_CONNECTION_TIMEOUT_MS: str = "MONGODB_CONNECTION_TIMEOUT_MS"
    MONGODB_DATABASE_NAME: str = "MONGODB_DATABASE_NAME"
    REPORT_COLLECTION_NAME: str = "REPORT_COLLECTION_NAME"
    SERVER_IP: str = "SERVER_IP"
    SERVER_PORT: str = "SERVER_PORT"
    LOGGER_FILENAME: str = "LOGGER_FILENAME"
